version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sm-url-shortner-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hj7gkqg64tea"
s3_prefix = "sm-url-shortner-demo"
region = "us-east-1"
profile = "960351580303_AdministratorAccess"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
