AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  url-shortner

  Sample SAM Template for url-shortner
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Resources:
  UrlShortnerCreator:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs14.x
      Handler: hello-world/app.lambdaHandler
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlShortnerTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref UrlShortnerTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /short_url
            Method: Post
  UrtShortnerRetrieve:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs14.x
      Handler: hello-world/app.lambdaHandler
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlShortnerTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref UrlShortnerTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{short_id}
            Method: Get
  UrlShortnerTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: short_id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   HelloWorldApi:
#     Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   HelloWorldFunction:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt HelloWorldFunctionRole.Arn
